CREATE TABLE public.state (
    id INT NOT NULL GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(50) NOT NULL,
    language_groups INT NOT NULL,
    created_date TIMESTAMP NOT NULL,
    modified_date TIMESTAMP NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.artist (
    id INT NOT NULL GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(800) NULL,
    age INT NOT NULL,
    state VARCHAR(50) NOT NULL,
    language_group VARCHAR(100) NOT NULL,
    created_date TIMESTAMP NOT NULL,
    modified_date TIMESTAMP NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.artefact (
    id INT NOT NULL GENERATED ALWAYS AS IDENTITY,
    artist VARCHAR(100) NOT NULL,
    title VARCHAR(100) NOT NULL,
    description VARCHAR(800) NULL,
    medium VARCHAR(50) NOT NULL,
    year INT NOT NULL,
    height_cm DECIMAL NOT NULL,
    width_cm DECIMAL NOT NULL,
    img_url VARCHAR(200) NULL,
    created_date TIMESTAMP NOT NULL,
    modified_date TIMESTAMP NOT NULL,
    PRIMARY KEY (id)
);

INSERT INTO public.state VALUES(DEFAULT, 'Victoria', 38, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO public.state VALUES(DEFAULT, 'New South Wales', 29, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO public.state VALUES(DEFAULT, 'Queensland', 50, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO public.state VALUES(DEFAULT, 'South Australia', 46, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO public.state VALUES(DEFAULT, 'Western Australia', 90, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO public.state VALUES(DEFAULT, 'Northern Territory', 100, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO public.state VALUES(DEFAULT, 'Australian Capital Territory', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO public.state VALUES(DEFAULT, 'Tasmania', 8, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);